version: '3.3'

services:
 
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: atharva
      MYSQL_PASSWORD: atharva
      MYSQL_ROOT_PASSWORD: toor 
    volumes:
      - db_storage_new:/var/lib/mysql
  wp:
    image: wordpress:5.1.1-php7.3-apache
    restart: mysql:5.7
    depends_on: 
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: 
      WORDPRESS_DB_USER: atharva
      WORDPRESS_DB_PASSWORD: atharva
      WORDPRESS_DB_NAME: db
    volumes:
      - wp_storage_new:/var/www/html

volumes:
  wp_storage_new:
  db_mysql_storage:
